# Generated by Django 5.2.5 on 2025-08-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='playerseasonstats',
            unique_together={('player', 'season')},
        ),
        migrations.CreateModel(
            name='HatTrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss'), ('Draw', 'Draw')], max_length=20)),
                ('date', models.DateField()),
                ('against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hat_tricks_against', to='stats.team')),
                ('for_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hat_tricks_for', to='stats.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
            options={
                'verbose_name_plural': 'hat-tricks',
            },
        ),
    ]
