# Generated by Django 5.2.5 on 2025-08-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_player_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseasonstats',
            name='assists',
        ),
    ]
