# Generated by Django 5.2.5 on 2025-08-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_remove_playerseasonstats_assists'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hattrick',
            unique_together={('player', 'for_team', 'against', 'date')},
        ),
    ]
