# Generated by Django 5.2.5 on 2025-08-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_hattrick_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
            options={
                'verbose_name_plural': 'clean sheets',
                'unique_together': {('player', 'season')},
            },
        ),
    ]
